name: lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  awesome-lint:
    strategy:
      fail-fast: false
      matrix:
        files:
          - "readme.md"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: "linting: ${{ matrix.files }}"
        run: npx -y awesome-lint ${{ matrix.files }}
  awesome-bot:
    strategy:
      fail-fast: false
      matrix:
        files:
          - "readme.md"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: "setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: "install awesome-bot"
        run: gem install awesome_bot
      - name: "linting: ${{ matrix.files }}"
        run: awesome_bot --allow-redirect --allow-dupe --white-list https://github.com/dcai/awesome-commandline-alternatives ${{ matrix.files }}
